"""cm_picks_bans

Revision ID: 1cb8b35fcb0
Revises: 58ebc7a4643
Create Date: 2018-07-22 00:37:52.649496

"""

# revision identifiers, used by Alembic.
revision = "1cb8b35fcb0"
down_revision = "58ebc7a4643"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cm_picks_bans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_pick", sa.Boolean(), nullable=False),
        sa.Column("is_radiant", sa.Boolean(), nullable=False),
        sa.Column("hero", sa.String(length=255), nullable=False),
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"], ["match.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hero", "match_id", name="cm_picks_bans_hero_match"),
    )
    op.add_column(
        "match", sa.Column("cm_captains", postgresql.ARRAY(sa.Integer()), nullable=True)
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "cm_captains")
    op.drop_table("cm_picks_bans")
    ### end Alembic commands ###
