"""empty message

Revision ID: 311d1f1983e
Revises:
Create Date: 2015-03-06 17:56:23.030633

"""

# revision identifiers, used by Alembic.
revision = '311d1f1983e'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


connection = op.get_bind()

season_stats_tbl = sa.Table(
    'season_stats',
    sa.MetaData(),
    sa.Column('id', sa.Integer, primary_key=True),
    sa.Column('longest_winstreak', sa.Integer),
    sa.Column('longest_losestreak', sa.Integer),
    sa.Column('longest_streak', sa.Integer)
)

player_match_stats_tbl = sa.Table(
    'player_match_stats',
    sa.MetaData(),
    sa.Column('id', sa.Integer, primary_key=True),
    sa.Column('season_stats_id', sa.Integer),
    sa.Column('pts_diff', sa.Integer)
)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season_stats', sa.Column('longest_winstreak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('season_stats', sa.Column('longest_losestreak', sa.Integer(), server_default='0', nullable=False))
    for season_stats in connection.execute(season_stats_tbl.select()):
        connection.execute(
            season_stats_tbl.update().where(season_stats_tbl.c.id == season_stats.id)\
                .values(longest_winstreak=season_stats.longest_streak)
        )

    for season_stats in connection.execute(season_stats_tbl.select()):
        pms = connection.execute(player_match_stats_tbl.select().where(
            player_match_stats_tbl.c.season_stats_id == season_stats.id).order_by(player_match_stats_tbl.c.id))
        pms = list(pms)
        longest = 0
        current = 0
        for e in pms:
            if e[2] < 0:
                current += 1
                if current > longest:
                    longest = current
            else:
                current = 0
        connection.execute(
            season_stats_tbl.update().where(season_stats_tbl.c.id == season_stats.id)\
                .values(longest_losestreak=longest)
        )
    op.drop_column('season_stats', 'longest_streak')


    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season_stats', sa.Column('longest_streak', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('season_stats', 'longest_winstreak')
    op.drop_column('season_stats', 'longest_losestreak')
    ### end Alembic commands ###
