"""cm_draft

Revision ID: 331474d5563
Revises: 58ebc7a4643
Create Date: 2018-07-21 17:16:44.499880

"""

# revision identifiers, used by Alembic.
revision = '331474d5563'
down_revision = '58ebc7a4643'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cm_draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_pick', sa.Boolean(), nullable=False),
    sa.Column('is_radiant', sa.Boolean(), nullable=False),
    sa.Column('hero', sa.String(length=255), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hero', 'match_id', name='cm_draft_hero_match')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cm_draft')
    ### end Alembic commands ###
