"""early_denies_last_hits_and_wards

Revision ID: 44a5e7bccc9
Revises: 4388c2d4416
Create Date: 2019-07-02 21:29:36.889808

"""

# revision identifiers, used by Alembic.
revision = '44a5e7bccc9'
down_revision = '4388c2d4416'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_match_stats', sa.Column('early_denies', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('early_last_hits', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('observer_wards_placed', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('sentry_wards_placed', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_match_stats', 'sentry_wards_placed')
    op.drop_column('player_match_stats', 'observer_wards_placed')
    op.drop_column('player_match_stats', 'early_last_hits')
    op.drop_column('player_match_stats', 'early_denies')
    ### end Alembic commands ###
