"""player match statsitems

Revision ID: 58ebc7a4643
Revises: d143e925e4
Create Date: 2017-11-06 06:29:33.409351

"""

# revision identifiers, used by Alembic.
revision = '58ebc7a4643'
down_revision = 'd143e925e4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_match_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_match_stats_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['player_match_stats_id'], ['player_match_stats.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_match_item')
    ### end Alembic commands ###
