"""add season places

Revision ID: 1b34c8c5dbc
Revises: 1505e9c853d
Create Date: 2015-08-13 16:59:17.286915

"""

# revision identifiers, used by Alembic.
revision = '1b34c8c5dbc'
down_revision = '1505e9c853d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



connection = op.get_bind()

season_stats_tbl = sa.Table(
    'season_stats',
    sa.MetaData(),
    sa.Column('id', sa.Integer, primary_key=True),
    sa.Column('season_id', sa.Integer),
    sa.Column('pts', sa.Integer),
    sa.Column('steam_id', sa.BigInteger)
)

season_tbl = sa.Table(
    'season',
    sa.MetaData(),
    sa.Column('id', sa.Integer, primary_key=True),
    sa.Column('ended', sa.DateTime),
    sa.Column('place_1', sa.BigInteger),
    sa.Column('place_2', sa.BigInteger),
    sa.Column('place_3', sa.BigInteger)
)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season', sa.Column('place_1', sa.BigInteger(), nullable=True))
    op.add_column('season', sa.Column('place_2', sa.BigInteger(), nullable=True))
    op.add_column('season', sa.Column('place_3', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'season', 'player', ['place_3'], ['steam_id'])
    op.create_foreign_key(None, 'season', 'player', ['place_2'], ['steam_id'])
    op.create_foreign_key(None, 'season', 'player', ['place_1'], ['steam_id'])

    for season in connection.execute(season_tbl.select().where(season_tbl.c.ended!=None)):
        stats = list(connection.execute(sa.select([season_stats_tbl.c.steam_id]).where(
            season_stats_tbl.c.season_id == season.id).order_by(sa.desc(season_stats_tbl.c.pts))\
            .limit(3)))
        connection.execute(
            season_tbl.update().where(season_tbl.c.id == season.id)\
                .values(place_1=stats[0][0], place_2=stats[1][0], place_3=stats[2][0])
            )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'season', type_='foreignkey')
    op.drop_constraint(None, 'season', type_='foreignkey')
    op.drop_constraint(None, 'season', type_='foreignkey')
    op.drop_column('season', 'place_3')
    op.drop_column('season', 'place_2')
    op.drop_column('season', 'place_1')
    ### end Alembic commands ###
