"""PlayerMatchStats +xp_per_min,gold_per_min,damage_taken fields

Revision ID: 1e87ca12c0a
Revises: 1b34c8c5dbc
Create Date: 2016-02-15 09:18:55.009080

"""

# revision identifiers, used by Alembic.
revision = '1e87ca12c0a'
down_revision = '1b34c8c5dbc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_match_stats', sa.Column('damage_taken', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('gold_per_min', sa.Integer(), nullable=True))
    op.add_column('player_match_stats', sa.Column('xp_per_min', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_match_stats', 'xp_per_min')
    op.drop_column('player_match_stats', 'gold_per_min')
    op.drop_column('player_match_stats', 'damage_taken')
    ### end Alembic commands ###
