"""dota tables rename

Revision ID: 33b6e2c95ff
Revises: 1e87ca12c0a
Create Date: 2017-01-17 14:40:22.230925

"""

# revision identifiers, used by Alembic.
revision = '33b6e2c95ff'
down_revision = '1e87ca12c0a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('player_match_stats', 'dota_player_match_stats')
    op.rename_table('player_match_rating', 'dota_player_match_rating')
    op.rename_table('match', 'dota_match')
    op.rename_table('season', 'dota_season')
    op.rename_table('season_stats', 'dota_season_stats')
    ### end Alembic commands ###


def downgrade():
    op.rename_table('dota_player_match_stats', 'player_match_stats')
    op.rename_table('dota_player_match_rating', 'player_match_rating')
    op.rename_table('dota_match', 'match')
    op.rename_table('dota_season', 'season')
    op.rename_table('dota_season_stats', 'season_stats')
