import bz2
from io import BytesIO
from urllib.request import urlopen

from flask import current_app

from gleague.api import create_app
from gleague.replays import ReplayParserService
from gleague.replays import ReplayDataProcessor
from tests import GleagueAppTestCase


REPLAY_DATA = {
    "match_id": 3214622621,
    "game_mode": 2,
    "start_time": 1496175169,
    "end_time": 1496175169,
    "duration": 3175,
    "radiant_win": False,
    "players": [
        {
            "account_id": 37658157,
            "account_id_orig": 76561197997923885,
            "hero_id": 30,
            "hero_name": "npc_dota_hero_witch_doctor",
            "kills": 2,
            "deaths": 8,
            "assists": 12,
            "last_hits": 25,
            "denies": 0,
            "level": 16,
            "player_slot": 0,
            "gold_per_min": 168,
            "xp_per_min": 238,
            "hero_damage": 5293,
            "hero_heal": 15329,
            "damage_taken": 19614,
            "tower_damage": 370,
            "observer_wards_placed": 17,
            "sentry_wards_placed": 14,
            "early_denies": 0,
            "early_last_hits": 2,
            "items": [
                "item_urn_of_shadows",
                "item_ward_dispenser",
                "item_cloak",
                "item_arcane_boots",
                "",
                "item_magic_wand",
            ],
            "movement": [],
            "networth": [],
            "xp": [],
        },
        {
            "account_id": 84853828,
            "account_id_orig": 76561198045119556,
            "hero_id": 85,
            "hero_name": "npc_dota_hero_undying",
            "kills": 8,
            "deaths": 6,
            "assists": 10,
            "last_hits": 79,
            "denies": 2,
            "level": 21,
            "player_slot": 1,
            "gold_per_min": 379,
            "xp_per_min": 368,
            "hero_damage": 10128,
            "hero_heal": 8144,
            "damage_taken": 21453,
            "tower_damage": 133,
            "observer_wards_placed": 3,
            "sentry_wards_placed": 2,
            "early_denies": 2,
            "early_last_hits": 2,
            "items": [
                "item_boots",
                "item_hand_of_midas",
                "item_sheepstick",
                "item_tpscroll",
                "item_pipe",
                "item_solar_crest",
            ],
            "movement": [],
            "networth": [],
            "xp": [],
        },
        {
            "account_id": 85937380,
            "account_id_orig": 76561198046203108,
            "hero_id": 11,
            "hero_name": "npc_dota_hero_nevermore",
            "kills": 4,
            "deaths": 6,
            "assists": 9,
            "last_hits": 461,
            "denies": 22,
            "level": 24,
            "player_slot": 2,
            "gold_per_min": 533,
            "xp_per_min": 515,
            "hero_damage": 32160,
            "hero_heal": 7040,
            "damage_taken": 29002,
            "tower_damage": 8064,
            "observer_wards_placed": 0,
            "sentry_wards_placed": 0,
            "early_denies": 15,
            "early_last_hits": 66,
            "items": [
                "item_black_king_bar",
                "item_satanic",
                "item_lesser_crit",
                "item_butterfly",
                "item_power_treads",
                "item_dragon_lance",
            ],
            "movement": [],
            "networth": [],
            "xp": [],
        },
        {
            "account_id": 117956848,
            "account_id_orig": 76561198078222576,
            "hero_id": 16,
            "hero_name": "npc_dota_hero_sand_king",
            "kills": 6,
            "deaths": 7,
            "assists": 11,
            "last_hits": 181,
            "denies": 5,
            "level": 21,
            "player_slot": 3,
            "gold_per_min": 341,
            "xp_per_min": 384,
            "hero_damage": 19571,
            "hero_heal": 1495,
            "damage_taken": 22999,
            "tower_damage": 0,
            "observer_wards_placed": 0,
            "sentry_wards_placed": 0,
            "early_denies": 4,
            "early_last_hits": 60,
            "items": [
                "",
                "item_tranquil_boots",
                "item_cyclone",
                "item_point_booster",
                "item_blink",
                "item_force_staff",
            ],
            "movement": [],
            "networth": [],
            "xp": [],
        },
        {
            "account_id": 94004717,
            "account_id_orig": 76561198054270445,
            "hero_id": 70,
            "hero_name": "npc_dota_hero_ursa",
            "kills": 2,
            "deaths": 9,
            "assists": 13,
            "last_hits": 319,
            "denies": 4,
            "level": 23,
            "player_slot": 4,
            "gold_per_min": 416,
            "xp_per_min": 449,
            "hero_damage": 14559,
            "hero_heal": 12308,
            "damage_taken": 35512,
            "tower_damage": 3228,
            "observer_wards_placed": 0,
            "sentry_wards_placed": 0,
            "early_denies": 3,
            "early_last_hits": 26,
            "items": [
                "item_vladmir",
                "item_blink",
                "item_basher",
                "item_desolator",
                "item_phase_boots",
                "item_ultimate_scepter",
            ],
            "movement": [],
            "networth": [],
            "xp": [],
        },
        {
            "account_id": 86974263,
            "account_id_orig": 76561198047239991,
            "hero_id": 64,
            "hero_name": "npc_dota_hero_jakiro",
            "kills": 4,
            "deaths": 5,
            "assists": 17,
            "last_hits": 121,
            "denies": 0,
            "level": 22,
            "player_slot": 128,
            "gold_per_min": 321,
            "xp_per_min": 408,
            "hero_damage": 15781,
            "hero_heal": 884,
            "damage_taken": 11611,
            "tower_damage": 2189,
            "observer_wards_placed": 18,
            "sentry_wards_placed": 9,
            "early_denies": 0,
            "early_last_hits": 9,
            "items": [
                "item_tranquil_boots",
                "item_tpscroll",
                "item_magic_wand",
                "item_force_staff",
                "item_cyclone",
                "item_gem",
            ],
            "movement": [],
            "networth": [],
            "xp": [],
        },
        {
            "account_id": 221666230,
            "account_id_orig": 76561198181931958,
            "hero_id": 13,
            "hero_name": "npc_dota_hero_puck",
            "kills": 14,
            "deaths": 1,
            "assists": 13,
            "last_hits": 431,
            "denies": 12,
            "level": 25,
            "player_slot": 129,
            "gold_per_min": 667,
            "xp_per_min": 517,
            "hero_damage": 42149,
            "hero_heal": 2326,
            "damage_taken": 11503,
            "tower_damage": 4692,
            "observer_wards_placed": 0,
            "sentry_wards_placed": 0,
            "early_denies": 10,
            "early_last_hits": 57,
            "items": [
                "item_cyclone",
                "item_dagon_5",
                "item_ultimate_scepter",
                "item_blink",
                "item_refresher",
                "item_travel_boots",
            ],
            "movement": [],
            "networth": [],
            "xp": [],
        },
        {
            "account_id": 236858633,
            "account_id_orig": 76561198197124361,
            "hero_id": 88,
            "hero_name": "npc_dota_hero_nyx_assassin",
            "kills": 2,
            "deaths": 5,
            "assists": 21,
            "last_hits": 80,
            "denies": 0,
            "level": 20,
            "player_slot": 130,
            "gold_per_min": 275,
            "xp_per_min": 338,
            "hero_damage": 17485,
            "hero_heal": 1494,
            "damage_taken": 16772,
            "tower_damage": 0,
            "observer_wards_placed": 3,
            "sentry_wards_placed": 1,
            "early_denies": 0,
            "early_last_hits": 9,
            "items": [
                "item_ancient_janggo",
                "item_energy_booster",
                "item_talisman_of_evasion",
                "item_blink",
                "item_force_staff",
                "item_travel_boots",
            ],
            "movement": [],
            "networth": [],
            "xp": [],
        },
        {
            "account_id": 108452107,
            "account_id_orig": 76561198068717835,
            "hero_id": 8,
            "hero_name": "npc_dota_hero_juggernaut",
            "kills": 6,
            "deaths": 4,
            "assists": 16,
            "last_hits": 350,
            "denies": 5,
            "level": 25,
            "player_slot": 131,
            "gold_per_min": 483,
            "xp_per_min": 521,
            "hero_damage": 28110,
            "hero_heal": 1502,
            "damage_taken": 18608,
            "tower_damage": 7846,
            "observer_wards_placed": 0,
            "sentry_wards_placed": 0,
            "early_denies": 1,
            "early_last_hits": 30,
            "items": [
                "item_blink",
                "item_manta",
                "item_skadi",
                "item_phase_boots",
                "item_monkey_king_bar",
                "item_ring_of_aquila",
            ],
            "movement": [],
            "networth": [],
            "xp": [],
        },
        {
            "account_id": 94364925,
            "account_id_orig": 76561198054630653,
            "hero_id": 65,
            "hero_name": "npc_dota_hero_batrider",
            "kills": 9,
            "deaths": 8,
            "assists": 19,
            "last_hits": 180,
            "denies": 1,
            "level": 24,
            "player_slot": 132,
            "gold_per_min": 357,
            "xp_per_min": 474,
            "hero_damage": 23111,
            "hero_heal": 3320,
            "damage_taken": 21273,
            "tower_damage": 290,
            "observer_wards_placed": 0,
            "sentry_wards_placed": 0,
            "early_denies": 1,
            "early_last_hits": 16,
            "items": [
                "item_blink",
                "item_force_staff",
                "item_urn_of_shadows",
                "",
                "item_refresher",
                "item_tranquil_boots",
            ],
            "movement": [],
            "networth": [],
            "xp": [],
        },
    ],
    "draft": {
        "captains": [0, 128],
        "picks_and_bans": [
            {"is_pick": False, "is_radiant": False, "hero": "npc_dota_hero_rattletrap"},
            {"is_pick": False, "is_radiant": True, "hero": "npc_dota_hero_bristleback"},
            {
                "is_pick": False,
                "is_radiant": False,
                "hero": "npc_dota_hero_crystal_maiden",
            },
            {"is_pick": False, "is_radiant": True, "hero": "npc_dota_hero_treant"},
            {
                "is_pick": True,
                "is_radiant": False,
                "hero": "npc_dota_hero_nyx_assassin",
            },
            {"is_pick": True, "is_radiant": True, "hero": "npc_dota_hero_witch_doctor"},
            {"is_pick": True, "is_radiant": True, "hero": "npc_dota_hero_sand_king"},
            {"is_pick": True, "is_radiant": False, "hero": "npc_dota_hero_jakiro"},
            {"is_pick": False, "is_radiant": True, "hero": "npc_dota_hero_warlock"},
            {
                "is_pick": False,
                "is_radiant": False,
                "hero": "npc_dota_hero_terrorblade",
            },
            {
                "is_pick": False,
                "is_radiant": True,
                "hero": "npc_dota_hero_life_stealer",
            },
            {
                "is_pick": False,
                "is_radiant": False,
                "hero": "npc_dota_hero_dragon_knight",
            },
            {"is_pick": True, "is_radiant": True, "hero": "npc_dota_hero_undying"},
            {"is_pick": True, "is_radiant": False, "hero": "npc_dota_hero_juggernaut"},
            {"is_pick": True, "is_radiant": True, "hero": "npc_dota_hero_ursa"},
            {"is_pick": True, "is_radiant": False, "hero": "npc_dota_hero_batrider"},
            {"is_pick": False, "is_radiant": True, "hero": "npc_dota_hero_lina"},
            {"is_pick": False, "is_radiant": False, "hero": "npc_dota_hero_slark"},
            {"is_pick": True, "is_radiant": False, "hero": "npc_dota_hero_puck"},
            {"is_pick": True, "is_radiant": True, "hero": "npc_dota_hero_nevermore"},
        ],
    },
}


class TestReplayParserService(GleagueAppTestCase):
    replay_url = "http://replay123.valve.net/570/3214622621_845489484.dem.bz2"

    @classmethod
    def _create_app(cls):
        return create_app("gleague_api_tests")

    def download_replay(self):
        response = urlopen(self.replay_url)
        data = response.read()
        data = BytesIO(bz2.decompress(data))
        data.seek(0)
        return data

    def test_when_parse_replay_then_ok(self):
        parser = ReplayParserService(current_app.config["REPLAY_PARSER_HOST"])
        data = parser.parse_replay(self.download_replay())
        for p in data["players"]:
            for key in ["movement", "networth", "xp"]:
                assert p.pop(key) is not None
                p[key] = []
        assert data == REPLAY_DATA


class TestReplayDataProcessor(GleagueAppTestCase):
    @classmethod
    def _create_app(cls):
        return create_app("gleague_api_tests")

    def test_when_save_replay_data_then_match_created(self):
        base_pts_diff = 10
        processor = ReplayDataProcessor(base_pts_diff, False)
        match = processor.save_replay_data(REPLAY_DATA)
        self.assertNotEqual(match, None)

        assert match.radiant_win is REPLAY_DATA["radiant_win"]
        assert match.game_mode == REPLAY_DATA["game_mode"]
        assert match.duration == REPLAY_DATA["duration"]
        assert match.start_time == REPLAY_DATA["start_time"]
        assert match.season_id is not None
        self.assertLength(10, match.players_stats)
